color: null
fieldLayouts:
  1f91db56-2a74-4151-8443-4fe3ff937aac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: edf10d2e-0ce3-4149-9d10-f6fa278d1aa6 # Blocks Builder - Rich Text - Heading
            handle: null
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05670d2d-f732-4c41-9fd8-1daaec6645bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 290a0c6b-f5e6-45ef-bb53-5a0518dd6027 # Blocks Builder - Rich Text - Copy
            handle: null
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c86797d2-c2d9-4b4c-88e4-a9ef2b59b0f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d325bb5-d99a-4266-9eac-a8d44c501ddf # Blocks Builder - Rich Text - Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: 'Text Alignment'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1b3f66e-be02-46d5-99ab-89a69f20e781
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 67fa8d96-3b70-4fdc-b773-e2bfa684de30 # Blocks Builder - Rich Text - Block Width
            handle: null
            includeInCards: false
            instructions: null
            label: 'Block Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d781ff8f-bbb7-4a52-99dd-52a645e7a58a
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 40ea4986-b95e-4a9a-bccc-c4cf0d52efcb
        userCondition: null
handle: richText
hasTitleField: false
icon: null
name: 'Rich Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
