columnSuffix: null
contentColumnType: string
handle: blocksBuilder
instructions: null
name: 'Blocks Builder'
searchable: false
settings:
  entryTypes:
    - 7421f819-5214-4079-9453-cdcd183975ed # Rich Text
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
